server:
  port: 8080

kafka:
  brokers:
    - localhost:9092
  topic: page-views
  version: "2.8.0"
  compression: snappy
  required_acks: -1
  max_message_bytes: 1000000
  retry_max: 5
  retry_backoff: 100ms

producer:

  default_mode: regular

  events_per_second: 5

  batch_size: 100
  batch_timeout: 5s

  error_rate: 0.05
  duplicate_rate: 0.01
  bounce_rate: 0.10

  regular_events_per_sec: 5
  peak_burst_size: 500
  peak_burst_interval: 5m
  night_events_interval: 10s

  page_id_pool: 500
  user_id_pool: 10000

  regions:
    - EU
    - US
    - ASIA
    - SA
    - AF
    - AU

  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    - "Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"
    - "Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1"